#!/bin/sh

set -e

#    -c      Include hash values of files in email
#    -e      Encrypt files with recipient's GPG key
#    -f FILE File to send as attachment in email
#    -s FROM Specifies the sending address of the email

usage(){
    cat << EOF
Usage: pgpmail [OPTION]... RECIPIENT ...

OPTIONS:
    -h      Display this message and exit
EOF
}

while getopts h arg; do
    case "$arg" in
        h) usage && exit 0 ;;
        *) usage && exit 0 ;;
    esac
done
