#!/bin/sh

set -e

#    -c      Include hash values of files in email
#    -e      Encrypt files with recipient's GPG key
#    -s FROM Specifies the sending address of the email

usage(){
    cat << EOF
Usage: pgpmail [OPTION]... RECIPIENT ...

OPTIONS:
    -f FILE File to send as attachment in email
    -h      Display this message and exit
EOF
}

ATTACHMENTS=""  # Empty list

while getopts f:h arg; do
    case "$arg" in
        f) ATTACHMENTS="${ATTACHMENTS} $OPTARG";;
        h) usage && exit 0 ;;
        *) usage && exit 0 ;;
    esac
done

ATTACHMENTS="${ATTACHMENTS#?}"
