#!/bin/sh

set -e


usage(){
    cat << EOF
Usage: pgpmail [OPTION]... -f FILE... -r RECIPIENT

REQUIRED:
    -f FILE     Path to file to include in email as attachment
    -r TO       Recipient of email

OPTIONS:
    -c          Include checksum of files in email
    -e          Encrypt files with recipient's GPG key
    -h          Display this message and exit
    -s FROM     Sender of email
EOF
    exit 0
}

verify_files(){
    # Verifies the files specified are indeed files
    for file in $FILES; do
        if [ ! -f "$file" ]; then
            echo "$0: '$file' not found"
            usage
        fi
    done
}

generate_attachments(){
    # Creates list of args to attach each file
    for file in $1; do
        ATTACHMENTS="${ATTACHMENTS} -A $file"
    done
    ATTACHMENTS="${ATTACHMENTS#?}"
}

hash_files(){
    # Loops through every file specified and appends a hash for each to a list
    for FILE in "$FILES"; do
        HASHES="${HASHES} $(sha256sum $FILE)"
    done
    HASHES="${HASHES#?}"
}

encrypt_attachments(){
    # generates encrypted versions of the files to attach
    [ ! "$(command -v gpg 2>/dev/null)" ] && echo "$0: gpg is not installed" && exit 1
    for file in $FILES; do
	gpg --encrypt --armor -r $RECIPIENT --yes $file
        ENCRYPTED="${ENCRYPTED} $file.asc"
    done
    ENCRYPTED="${ENCRYPTED#?}"
}

send_email(){
    [ ! "$(command -v mail 2>/dev/null)" ] && echo "$0: mailutils is not installed" && exit 1
    [ ! "$RECIPIENT" ] && echo "$0: no recipient specified" && usage


    [ "$HASH" ] && hash_files; echo "$HASHES" | mail \
        -s "$SUBJECT" \
        `[ "$SENDER" ] && echo  " -r $SENDER"` \
        `if [ "$FILES" ]; then
                verify_files
                if [ "$ENCRYPT" ]; then
            	    encrypt_attachments
            	    generate_attachments "$ENCRYPTED"
                else
            	    generate_attachments "$FILES"
                fi
        	echo "$ATTACHMENTS"
        fi` \
        "$RECIPIENT" 
}

SUBJECT="$(date) pgpmail"

while getopts cef:hr:s: arg; do
    case "$arg" in
        c) HASH=1 ;;
        e) ENCRYPT=1 ;;
        f) FILES="${FILES} $OPTARG" ;;
        h) usage ;;
        r) RECIPIENT="$OPTARG" ;;
        s) SENDER="$OPTARG" ;;
        ?) usage ;;
    esac
done

FILES="${FILES#?}"

send_email
